# Generated by Django 3.2.6 on 2021-09-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=20)),
                ('d_description', models.CharField(max_length=20)),
                ('d_createDate', models.DateTimeField()),
                ('d_isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10, unique=True)),
                ('u_password', models.CharField(max_length=256, unique=True)),
                ('u_gender', models.BooleanField(default=True)),
                ('u_age', models.IntegerField(default=5)),
                ('u_isDelete', models.BooleanField(default=False)),
                ('u_dept', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myApp.departments')),
            ],
        ),
    ]
