# Generated by Django 3.2.6 on 2021-09-08 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='departments',
            managers=[
                ('deptObj2', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='departments',
            name='d_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_password',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name='departments',
            table='depts',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='headshots')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.users')),
            ],
            options={
                'db_table': 'usersprofile',
            },
        ),
    ]
