# Generated by Django 3.2.6 on 2021-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmall', '0004_newfind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfind',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
