# Generated by Django 3.2.6 on 2021-10-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmall', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=10)),
                ('productName', models.CharField(max_length=100)),
                ('productImg', models.CharField(max_length=150)),
                ('discountPrice', models.CharField(max_length=10)),
                ('originalPrice', models.CharField(max_length=10)),
                ('categoryId', models.CharField(max_length=10)),
                ('childId', models.CharField(max_length=10)),
                ('childName', models.CharField(max_length=10)),
                ('shopLocation', models.CharField(max_length=10)),
                ('sales', models.CharField(max_length=10)),
                ('hot', models.FloatField()),
                ('inventory', models.IntegerField()),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='productTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeId', models.CharField(max_length=10)),
                ('typeName', models.CharField(max_length=12)),
                ('img', models.CharField(max_length=150)),
                ('childType', models.CharField(max_length=300)),
                ('typeSort', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
