# Generated by Django 3.2.6 on 2021-10-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmall', '0008_alter_producttypes_childtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
