# Generated by Django 3.2.6 on 2021-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmall', '0010_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test1',
            field=models.FloatField(),
        ),
    ]
