# Generated by Django 3.2.6 on 2021-10-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmall', '0011_alter_test_test1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discountPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='originalPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='sales',
            field=models.IntegerField(),
        ),
    ]
