# Generated by Django 3.2.6 on 2021-10-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmall', '0013_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
