# Generated by Django 3.2.6 on 2021-10-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmall', '0014_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20)),
                ('productId', models.CharField(max_length=10)),
                ('productNum', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('isChoose', models.BooleanField(default=True)),
                ('productImg', models.CharField(max_length=150)),
                ('productName', models.CharField(max_length=100)),
                ('orderId', models.CharField(default='0', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
